config/routes.rb
Rails.application.routes.draw do
  root 'access#index'
  
  get 'parameters/index'

  get 'parameters/show'

  get 'parameters/new'

  get 'parameters/edit'

  get 'parameters/delete'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :committees do
    member do
      get :delete
    end
  end
  
   resources :sponsors do
    member do
      get :delete
    end
  end
  
  resources :events do
    member do
      get :delete
    end
  end
  
  resources :positions do
    member do
      get :delete
    end
  end
  
  resources :divisions do
    member do
      get :delete
    end
  end
  
  resources :members do
    member do
      get :delete
    end
  end
  
  resources :parameters do
    member do
      get :delete
    end
  end

end

app/models/position.rb
class Position < ActiveRecord::Base
    has_attached_file :image, styles: {small: "150x150#"}
    validates_attachment_content_type :image, :content_type => ["image/jpeg","image/png"]
    has_many :members
    validates_presence_of :name
    validates_length_of :name, :maximum => 50
    validates_presence_of :pos_type
    validates_length_of :pos_type, :maximum => 50
    validates_presence_of :major
    validates_length_of :major, :maximum => 50
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  
  layout "admin"
  before_action :confirm_logged_in
  
  # ***********************************************************************
  # Display positions.
  # ***********************************************************************
  def index
    @positions = Position.order(:id)
  end

  def show
    @position = Position.find(params[:id])
  end

  # ***********************************************************************
  # Add a new position.
  # ***********************************************************************
  def new
    @position = Position.new
  end
  
  def create
     @position = Position.new(position_params)

    if @position.save
      redirect_to(positions_path)
    else
      render("new")
    end
  end

  # ***********************************************************************
  # Update a position.
  # ***********************************************************************
  def edit
    @position = Position.find(params[:id])
  end
  
  def update
    @position = Position.find(params[:id])

    if @position.update_attributes(position_params)
      redirect_to(position_path(@position))
    else
      render("edit")
    end
  end

  # ***********************************************************************
  # Delete a position.
  # ***********************************************************************
  def delete
    @position = Position.find(params[:id])
  end
  
  def destroy
    @position = Position.find(params[:id])
    @position.destroy
    redirect_to(positions_path)
  end
  
  # ***********************************************************************
  # Other support methods.
  # ***********************************************************************
  private
  
  def position_params
    params.require(:position).permit(:name, :pos_type, :major, :image)
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/delete.html.erb
<div>
    <h2>Delete Position</h2>
    
    <%= form_for(@position, :method => "delete") do |f| %>
        <p class="divCenter">Are you sure you want to permanently delete this position?</p>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel boldText">Name:</td>
                <td><%= @position.name %></td>
            </tr>
            <tr>
                <td class="columnLabel boldText">Type:</td>
                <td><%= @position.pos_type %></td>
            </tr>
            <tr>
                <td class="columnLabel boldText">Major:</td>
                <td><%= @position.major %></td>
            </tr> 
        </table>
        <div class="divCenter">
            <%= f.submit("Delete Position", :class => "btn btn-danger btn-sm") %>
            <%= link_to("Back to List", positions_path, :class => "btn btn-warning btn-sm") %>
        </div>
    <% end %>
</div>

app/views/positions/edit.html.erb
<div>
    <h2>Update Position</h2>
    <%= form_for @position, html: {multipart: true } do |f| %>
        <%= error_messages_for(f.object) %>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel">Name</td>
                <td><%= f.text_field(:name, size: 40) %></td>
            </tr>
            <tr>
                <td class="columnLabel">Type</td>
                <td><%= f.text_field(:pos_type, size: 40) %></td>
            </tr>
            <tr>
                <td class="columnLabel">Major</td>
                <td><%= f.text_field(:major, size: 40) %></td>
            </tr>   
            <tr>
                <td class="columnLabel">Picture</td>
                <td><%= f.file_field :image %></td>
            </tr>
        </table>
        
        <div class="divCenter">
            <%= f.submit("Update Type", :class => "btn btn-success btn-sm") %>
            <%= link_to("Back to List", positions_path, :class => "btn btn-warning btn-sm") %>
        </div>
    <% end %>
</div>

app/views/positions/index.html.erb
<div>
    <h2>Positions</h2>
    <table class="table table-condensed table-striped table-bordered">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Type</th>
            <th>Major</th> 
            <th></th>
        </tr>
        <% @positions.each do |position| %>
        <tr>
            <td><%= position.id %></td>
            <td><%= position.name %></td>
            <td><%= position.pos_type %></td>
            <td><%= position.major %></td> 
            <td>
                <%= link_to("Show", position_path(position.id), :class => "btn btn-primary btn-xs") %>
                <%= link_to("Edit", edit_position_path(position.id), :class => "btn btn-primary btn-xs") %>
                <%= link_to("Delete", delete_position_path(position.id), :class => "btn btn-danger btn-xs") %>
            </td>
        </tr>
        <% end %>
    </table>
    <%= link_to("Add new position", new_position_path, :class => "btn btn-sm btn-success") %>
    <%= link_to("Back to menu", access_menu_path, :class => "btn btn-sm btn-warning")%>
</div>

app/views/positions/new.html.erb
<div>
    <h2>Create Position</h2>
     <%= form_for @position, html: {multipart: true } do |f| %>
        <%= error_messages_for(f.object) %>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel">Name</td>
                <td><%= f.text_field(:name, size: 40) %></td>
            </tr>
            <tr>
                <td class="columnLabel">Type</td>
                <td><%= f.text_field(:pos_type, size: 40) %></td>
            </tr>
            <tr>
                <td class="columnLabel">Major</td>
                <td><%= f.text_field(:major, size: 40) %></td>
             </tr>
             <tr> 
                <td class="columnLabel">Picture</td>
                <td><%= f.file_field :image %></td>
            </tr>
        </table>
        
        <div class="divCenter">
            <%= f.submit("Create Type", :class => "btn btn-success btn-sm") %>
            <%= link_to("Back to List", positions_path, :class => "btn btn-warning btn-sm") %>
        </div>
    <% end %>
</div>

app/views/positions/show.html.erb
<div>
    <h2>Show Position</h2>
    
    <table class="tableCenter">
        <tr>
              <td class="columnLabel boldText">Picture:</td>
            <td><%=image_tag @position.image.url(:small) %></td> 
        </tr> 
        <tr>
            <td class="columnLabel boldText">Name:</td>
            <td><%= @position.name %></td>
        </tr>
        <tr>
            <td class="columnLabel boldText">Type:</td>
            <td><%= @position.pos_type %></td>
        </tr>
        <tr>
            <td class="columnLabel boldText">Major:</td>
            <td><%= @position.major %></td>
        </tr>
    </table>
    
    <div class="divCenter">
        <%= link_to("Back to list", positions_path, :class => "btn btn-warning btn sm") %>    
    </div>
</div>