config/routes.rb
Rails.application.routes.draw do
  root 'access#index'
  
  get 'parameters/index'

  get 'parameters/show'

  get 'parameters/new'

  get 'parameters/edit'

  get 'parameters/delete'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :committees do
    member do
      get :delete
    end
  end
  
   resources :sponsors do
    member do
      get :delete
    end
  end
  
  resources :events do
    member do
      get :delete
    end
  end
  
  resources :positions do
    member do
      get :delete
    end
  end
  
  resources :divisions do
    member do
      get :delete
    end
  end
  
  resources :members do
    member do
      get :delete
    end
  end
  
  resources :parameters do
    member do
      get :delete
    end
  end

end

app/models/division.rb
class Division < ActiveRecord::Base
    has_many :members
    validates_presence_of :name
    validates_length_of :name, :maximum => 30
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  
  layout "admin"
  before_action :confirm_logged_in
  
  # ***********************************************************************
  # Display divisions.
  # ***********************************************************************
  def index
    @divisions = Division.order(:id)
  end

  def show
     @division = Division.find(params[:id])
  end
  
  # ***********************************************************************
  # Add a new division.
  # ***********************************************************************
  def new
    @division = Division.new
  end
  
  def create
     @division = Division.new(division_params)

    if @division.save
      redirect_to(divisions_path)
    else
      render("new")
    end
  end
  
  # ***********************************************************************
  # Update a division.
  # ***********************************************************************
  def edit
    @division = Division.find(params[:id])
  end
  
  def update
    @division = Division.find(params[:id])

    if @division.update_attributes(division_params)
      redirect_to(division_path(@division))
    else
      render("edit")
    end
  end
  
  # ***********************************************************************
  # Delete a division.
  # ***********************************************************************
  def delete
    @division = Division.find(params[:id])
  end
  
  def destroy
    @division = Division.find(params[:id])
    @division.destroy
    redirect_to(divisions_path)
  end
  
  # ***********************************************************************
  # Other support methods.
  # ***********************************************************************
  private
  
  def division_params
    params.require(:division).permit(:name, :description)
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/delete.html.erb
<div>
    <h2>Delete Division</h2>
    
    <%= form_for(@division, :method => "delete") do |f| %>
        <p class="divCenter">Are you sure you want to permanently delete this division?</p>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel boldText">Name:</td>
                <td><%= @division.name %></td>
            </tr>
            <tr>
                <td class="columnLabel boldText">Description:</td>
                <td><%= @division.description %></td>
            </tr>
        </table>
        <div class="divCenter">
            <%= f.submit("Delete Division", :class => "btn btn-danger btn-sm") %>
            <%= link_to("Back to List", divisions_path, :class => "btn btn-warning btn-sm") %>
        </div>
    <% end %>
</div>

app/views/divisions/edit.html.erb
<div>
    <h2>Update Division</h2>
    <%= form_for(@division) do |f| %>
        <%= error_messages_for(f.object) %>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel">Name</td>
                <td><%= f.text_field(:name, size: 40) %></td>
            </tr>
            <tr>
                <td class="columnLabel">Description</td>
                <td><%= f.text_area(:description, cols: 43, rows: 10) %></td>
            </tr>
        </table>
        
        <div class="divCenter">
            <%= f.submit("Update Division", :class => "btn btn-success btn-sm") %>
            <%= link_to("Back to List", divisions_path, :class => "btn btn-warning btn-sm") %>
        </div>
    <% end %>
</div>

app/views/divisions/index.html.erb
<div>
    <h2>Divisions</h2>
   
    <table class="table table-condensed table-striped table-bordered">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th></th>
        </tr>
        <% @divisions.each do |division| %>
        <tr>
            <td><%= division.id %></td>
            <td><%= division.name %></td>
            <td><%= division.description %></td>
            <td>
                <%= link_to("Show", division_path(division.id), :class => "btn btn-primary btn-xs") %>
                <%= link_to("Edit", edit_division_path(division.id), :class => "btn btn-primary btn-xs") %>
                <%= link_to("Delete", delete_division_path(division.id), :class => "btn btn-danger btn-xs") %>
            </td>
        </tr>
        <% end %>
    </table>
     <%= link_to("Add new division", new_division_path, :class => "btn btn-sm btn-success") %>
     <%= link_to("Back to menu", access_menu_path, :class => "btn btn-sm btn-warning")%>
</div>

app/views/divisions/new.html.erb
<div>
    <h2>Create Division</h2>
    <%= form_for(@division) do |f| %>
        <%= error_messages_for(f.object) %>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel">Name</td>
                <td><%= f.text_field(:name, size:40) %></td>
            </tr>
            <tr>
                <td class="columnLabel">Description</td>
                <td><%= f.text_area(:description, cols: 43, rows: 10) %></td>
            </tr>
        </table>
        
        <div class="divCenter">
            <%= f.submit("Create Division", :class => "btn btn-success btn-sm") %>
            <%= link_to("Back to List", divisions_path, :class => "btn btn-warning btn-sm") %>
        </div>
    <% end %>
</div>

app/views/divisions/show.html.erb
<div>
    <h2>Show Division</h2>
    
    <table class="tableCenter">
        <tr>
            <td class="columnLabel boldText">Name:</td>
            <td><%= @division.name %></td>
        </tr>
        <tr>
            <td class="columnLabel boldText">Description:</td>
            <td><%= @division.description %></td>
        </tr>
    </table>
    
    <div class="divCenter">
        <%= link_to("Back to list", divisions_path, :class => "btn btn-warning btn-sm") %>
    </div>
</div>