config/routes.rb
Rails.application.routes.draw do
  root 'access#index'
  
  get 'parameters/index'

  get 'parameters/show'

  get 'parameters/new'

  get 'parameters/edit'

  get 'parameters/delete'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :committees do
    member do
      get :delete
    end
  end
  
   resources :sponsors do
    member do
      get :delete
    end
  end
  
  resources :events do
    member do
      get :delete
    end
  end
  
  resources :positions do
    member do
      get :delete
    end
  end
  
  resources :divisions do
    member do
      get :delete
    end
  end
  
  resources :members do
    member do
      get :delete
    end
  end
  
  resources :parameters do
    member do
      get :delete
    end
  end

end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  
  layout "admin"
  
  before_action :add_initial_user
  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
  #skip_before_action :verify_authenticity_token
  # ***********************************************************************
  # Display menu items.
  # ***********************************************************************
  def menu
   @sponsors = Sponsor.order(:name)
  end

  # ***********************************************************************
  # Display login form.
  # ***********************************************************************
  def login
  end
   # ***********************************************************************
  # Index
  # ***********************************************************************
  def index
    @committees = Committee.order(:name)
    @sponsors = Sponsor.order(:name)
    @events = Event.order(params[:id])
    @positions = Position.order(:id)
    @members = Member.order(:id)
  end
  # ***********************************************************************
  # Validate user credentials..
  # ***********************************************************************
  def attempt_login
    if params[:email].present? && params[:password].present?
      found_user = Member.where(:email => params[:email]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end
    
    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "You are logged in."
      redirect_to(admin_path)
    else
      flash.now[:notice] = "Invalid email/password combination."
      render("login")
    end
  end
  
  # ***********************************************************************
  # Terminate user login session.
  # ***********************************************************************
  def logout
    session[:user_id] = nil
    flash[:notice] = "Logged out."
    redirect_to(access_login_path)
  end
  
  private
  
  # ***********************************************************************
  # Add initial user, initial position and initial division.
  # An initial user account is required (with initial position and division),
  # otherwise it is not possible to login.
  # ***********************************************************************
  def add_initial_user
    initial_user = Member.where(:email => "administrator@administrator.com").first
    
    unless initial_user
        # Create an initial position.
        position = Position.new
        position.name = "Administrator"
        position.pos_type = "Administrator"
        position.save
        
        # Create an initial division.
        division = Division.new
        division.name = "Administrator"
        division.save
        
        # Find initial position and division created.
        # Id´s will be used to crete initial user.
        position = Position.where(:name => "Administrator").first
        division = Division.where(:name => "Administrator").first
      
        # Create an initial user with position and divison created above.
        member = Member.new
        member.name = "Administrator"
        member.email = "administrator@administrator.com"
        member.password = "administrator"
        member.major = "NONE"
        member.grad_year = 9999
        member.member_since = 9999
        member.hometown = "NONE"
        member.position_id = position.id
        member.division_id = division.id
        member.save
    end
  end
  
  
end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SEC Portal</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="/d+N9gl9AT0qxWmS8hZLWW3YVyod7vP+mjV4jaNfE8lmGCt55xfAZ2tGrehESGUZMqWPXoAGlreweNA+eIbgJw==" />
</head>
<body>

 <!--Login Display------------------------------------------------------------------------------------------>
   
    <div class="container" style="padding-top:200px;">
        <h3 class="text-center"  style="padding-left:75px;">Login</h3>
        <form class="form-horizontal" action="/access/attempt_login" accept-charset="UTF-8" method="post">
            <input name="UTF-8" type="hidden" value="&#x2713;" />
            <input  type ="hidden" name="authenticity_token" value = "<%= form_authenticity_token %>"  />
            <!--  -->
            <div class="form-group">
                <label class="contro-label col-sm-offset-3 col-sm-1" for="email">Email:</label>
                <div class="col-sm-5">
                    <input type="email" name="email" class="form-control" id="email" placeholder="Enter email">
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-sm-offset-3 col-sm-1" for="password">Password:</label>
                <div class="col-sm-5">
                    <input type="password" name="password" class="form-control" id="password" placeholder="Enter password">
                </div>
            </div>
            
          <!--  <div class="form-group">
                <div class="col-sm-offset-4 col-sm-10">
                    <div class="checkbox">
                        <label><input type="checkbox">Remember me</label>
                    </div>
                </div>
            </div> -->
            
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-5">
                    <button  type="submit" name="commit" class="btn btn-primary btn-block" background-color:"#500000" >Log in</button>
                </div>
            </div>
            
        </form>
    </div>
    
</body>    
</html>

<!--
<div>
    <h2>Login</h2>
    <%= form_tag(access_attempt_login_path, :method => :post) do %>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel"><%= label_tag(:email) %></td>
                <td><%= text_field_tag(:email, params[:email]) %></td>
            </tr>
            <tr>
                <td class="columnLabel"><%= label_tag(:password) %></td>
                <td><%= password_field_tag(:password) %></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><%= submit_tag("Log In") %></td>
            </tr>
        </table>
    <% end %>
</div>
-->

app/views/access/menu.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Admin Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

   <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!--- Indicators
       <ol class="carousel-indicators">
           <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
           <li data-target="#carousel-example-generic" data-slide-to="1"></li>
           <li data-target="#carousel example-generic" data-slid-to="2"></li>
       </ol>
       
       <!-- wrapper for slides -->
       <!-- creating the active picture class by making the first sponsor in the database call -->
       <!-- 
       <div class="carousel-inner">
           <div class="item active">
               <p class="col-sm-offset-5 col-sm-6">
               <img src=<%#= @sponsors[0].image.url(:small) %>, class="image-rounded" alt="active image">
               </p>
               <h3 class="col-md-8 col-sm-10 col-xs-12 col-md-offset-2 col-sm-offset-1">
                    <font color="500000">
                        <b><#%= @sponsors[0].name %></b>
                    </font>
                </h3>
                <p class="col-sm-offset-5 col-sm-2">
                    <font size="-1" color="000000">
                        <%#= @sponsors[0].spn_type %> Sponsor
                    </font>
                </p>
           </div>
           -->
           
           <!-- creating the rest of the carousel for the rest of the items in the database --> 
           <!--
           <%# @sponsors[1..@sponsors.size].each do |sponsor| %>
           <div class="item">
               <p class="col-sm-offset-5 col-sm-6">
                   <img src=<%#= sponsor.image.url(:small) %> alt="el Koala">
               </p>
               
                <h3 class="col-md-8 col-sm-10 col-xs-12 col-md-offset-2 col-sm-offset-1">
                    <font color="500000">
                        <b><%#= sponsor.name %></b>
                    </font>
                </h3>
                
                <p class="col-md-8 col-sm-10 col-xs-12 col-md-offset-2 col-sm-offset-1"> <!-- description of sponsor -->
                
            <!--                <%#= sponsor.description %>
                </p>
           </div>
          
           <%# end %>
       </div>
       -->
       <!-- controls -->
       <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
           <span class="glyphicon glyphicon-menu-left"></span>
       </a>
       <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
           <span class= "glyphicon glyphicon-menu-right"></span>
       </a>
   </div> 

<div> 
</body>
<body>
    <%= flash[:notice] %>
    <h2>Admin Menu</h2>
    
    <table class="tableCenter">
        <tr>
            <td>
                <%= link_to("Manage Committees", committees_path) %>    
            </td>
        </tr>
        <tr>
            <td>
                <%= link_to("Manage Divisions", divisions_path) %>    
            </td>
        </tr>
        <tr>
            <td>
                <%= link_to("Manage Events", events_path) %>    
            </td>
        </tr>
        <tr>
            <td>
                <%= link_to("Manage Positions", positions_path) %>  
            </td>
        </tr>
        <tr>
            <td>
                <%= link_to("Manage Sponsors", sponsors_path) %>  
            </td>
        </tr>
        <tr>
            <td>
                <%= link_to("Manage Members", members_path) %>   
            </td>
        </tr>
        <tr>
            <td>
                <%= link_to("Logout", access_logout_path) %>   
            </td>
        </tr>
    </table>

</div>

</body>
</html>