config/routes.rb
Rails.application.routes.draw do
  root 'access#index'
  
  get 'parameters/index'

  get 'parameters/show'

  get 'parameters/new'

  get 'parameters/edit'

  get 'parameters/delete'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :committees do
    member do
      get :delete
    end
  end
  
   resources :sponsors do
    member do
      get :delete
    end
  end
  
  resources :events do
    member do
      get :delete
    end
  end
  
  resources :positions do
    member do
      get :delete
    end
  end
  
  resources :divisions do
    member do
      get :delete
    end
  end
  
  resources :members do
    member do
      get :delete
    end
  end
  
  resources :parameters do
    member do
      get :delete
    end
  end

end

app/models/committee.rb
class Committee < ActiveRecord::Base
    validates_presence_of :name
    validates_length_of :name, :maximum => 50
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  
  layout "admin"
  before_action :confirm_logged_in
  
  # ***********************************************************************
  # Display committees.
  # ***********************************************************************
  def index
    @committees = Committee.order(:name)
  end

  def show
    @committee = Committee.find(params[:id])
  end

  # ***********************************************************************
  # Add a new committee.
  # ***********************************************************************
  def new
    @committee = Committee.new
  end
  
  def create
     @committee = Committee.new(committee_params)

    if @committee.save
      redirect_to(committees_path)
    else
      render("new")
    end
  end

  # ***********************************************************************
  # Update a committee.
  # ***********************************************************************
  def edit
    @committee = Committee.find(params[:id])
  end
  
  def update
    @committee = Committee.find(params[:id])

    if @committee.update_attributes(committee_params)
      redirect_to(committee_path(@committee))
    else
      render("edit")
    end
  end

  # ***********************************************************************
  # Delete a committee.
  # ***********************************************************************
  def delete
    @committee = Committee.find(params[:id])
  end
  
  def destroy
    @committee = Committee.find(params[:id])
    @committee.destroy
    redirect_to(committees_path)
  end
  
  # ***********************************************************************
  # Other support methods.
  # ***********************************************************************
  private
  
  def committee_params
    params.require(:committee).permit(:name, :image, :description)
  end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/delete.html.erb
<div>
    <h2>Delete Committee</h2>
    
    <%= form_for(@committee, :method => "delete") do |f| %>
        <p class="divCenter">Are you sure you want to permanently delete this committee?</p>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel boldText">Name:</td>
                <td><%= @committee.name %></td>
            </tr>
            <tr>
                <td class="columnLabel boldText">Description:</td>
                <td><%= @committee.description %></td>
            </tr>
        </table>
        <div class="divCenter">
            <%= f.submit("Delete Committee", :class => "btn btn-danger btn-sm") %>
            <%= link_to("Back to List", committees_path, :class => "btn btn-warning btn-sm") %>
        </div>
    <% end %>
</div>

app/views/committees/edit.html.erb
<div>
    <h2>Update Committee</h2>
    <%= form_for(@committee) do |f| %>
        <%= error_messages_for(f.object) %>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel">Name</td>
                <td><%= f.text_field(:name, size: 40) %></td>
            </tr>
            <tr>
                <td class="columnLabel">Description</td>
                <td><%= f.text_area(:description , cols: 43, rows: 10) %></td>
            </tr>
        </table>
        <div class="divCenter">
            <%= f.submit("Update Committee", :class => "btn btn-success btn-sm") %>
            <%= link_to("Back to List", committees_path, :class => "btn btn-warning btn-sm") %>
        </div>
    <% end %>
    
</div>

app/views/committees/index.html.erb
<div>
    <h2>Committees</h2>
    <table class="table table-condensed table-bordered table-striped">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th></th>
        </tr>
        <% @committees.each do |committee| %>
        <tr>
            <td><%= committee.id %></td>
            <td><%= committee.name %></td>
            <td><%= committee.description %></td>
            <td>
                <%= link_to("Show", committee_path(committee.id), :class => "btn btn-primary btn-xs") %>
                <%= link_to("Edit", edit_committee_path(committee.id), :class => "btn btn-primary btn-xs") %>
                <%= link_to("Delete", delete_committee_path(committee.id), :class => "btn btn-danger btn-xs") %>
            </td>
        </tr>
        <% end %>
    </table>
    <%= link_to("Add new committee", new_committee_path, :class => "btn btn-success btn-sm") %>
    <%= link_to("Back to menu", access_menu_path, :class => "btn btn-sm btn-warning")%>
</div>

app/views/committees/new.html.erb
<div>
    <h2>Create Committee</h2>
    <%= form_for(@committee) do |f| %>
        <%= error_messages_for(f.object) %>
        <table class="tableCenter">
            <tr>
                <td class="columnLabel">Name</td>
                <td><%= f.text_field(:name, size: 40) %></td>
            </tr>
            <tr>
                <td class="columnLabel">Description</td>
                <td><%= f.text_area(:description, cols: 43, rows: 10) %></td>
            </tr>
        </table>
        
        <div class="divCenter">
            <%= f.submit("Create Committee", :class => "btn btn-success btn-sm") %>
            <%= link_to("Back to List", committees_path, :class => "btn btn-warning btn-sm") %>
        </div>
    <% end %>
</div>

app/views/committees/show.html.erb
<div>
    <h2>Show Committee</h2>
    
    <table class="tableCenter">
        <tr>
            <td class="columnLabel boldText">Name:</td>
            <td><%= @committee.name %></td>
        </tr>
        <tr>
            <td class="columnLabel boldText">Description:</td>
            <td><%= @committee.description %></td>
        </tr>
    </table>
    
    <div class="divCenter">
        <%= link_to("Back to list", committees_path, :class => "btn btn-warning btn-sm") %>
    </div>
</div>